DROP TABLE IF EXISTS sdata.sse_idx_quote;
CREATE TABLE sdata.sse_idx_quote
(
	MDStreamID         CHAR(5),
	SecurityID         CHAR(6),
	Symbol             CHAR(8),
	TradeVolume        DECIMAL(16),
	TotalValueTraded   DECIMAL(16,2),
	PreClosePx         DECIMAL(11,4),
	OpenPrice          DECIMAL(11,4),
	HighPrice          DECIMAL(11,4),
	LowPrice           DECIMAL(11,4),
	TradePrice         DECIMAL(11,4),
	ClosePx            DECIMAL(11,4),
	TradingPhaseCode   CHAR(8),
	TS          CHAR(12)
) PARTITIONED BY (TRADDATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
STORED AS TEXTFILE
;

DROP TABLE IF EXISTS sdata.sse_sec_quote;
CREATE TABLE sdata.sse_sec_quote
(
	MDStreamID         CHAR(5),
	SecurityID         CHAR(6),
	Symbol             CHAR(8),
	TradeVolume        DECIMAL(16),
	TotalValueTraded   DECIMAL(16,2),
	PreClosePx         DECIMAL(11,3),
	OpenPrice          DECIMAL(11,3),
	HighPrice          DECIMAL(11,3),
	LowPrice           DECIMAL(11,3),
	TradePrice         DECIMAL(11,3),
	ClosePx            DECIMAL(11,3),
	BuyPrice1          DECIMAL(11,3),
	BuyVolume1         DECIMAL(12),
	SellPrice1         DECIMAL(11,3),
	SellVolume1        DECIMAL(12),
	BuyPrice2          DECIMAL(11,3),
	BuyVolume2         DECIMAL(12),
	SellPrice2         DECIMAL(11,3),
	SellVolume2        DECIMAL(12),
	BuyPrice3          DECIMAL(11,3),
	BuyVolume3         DECIMAL(12),
	SellPrice3         DECIMAL(11,3),
	SellVolume3        DECIMAL(12),
	BuyPrice4          DECIMAL(11,3),
	BuyVolume4         DECIMAL(12),
	SellPrice4         DECIMAL(11,3),
	SellVolume4        DECIMAL(12),
	BuyPrice5          DECIMAL(11,3),
	BuyVolume5         DECIMAL(12),
	SellPrice5         DECIMAL(11,3),
	SellVolume5        DECIMAL(12),
	PreCloseIOPV       DECIMAL(11,3),
	IOPV               DECIMAL(11,3),
	TradingPhaseCode   CHAR(8),
	TS          CHAR(12)
) PARTITIONED BY (TRADDATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
STORED AS TEXTFILE
;


DROP TABLE IF EXISTS sdata.szse_sec_quote;
CREATE TABLE sdata.szse_sec_quote
(
	HQZQDM	CHAR(6),
	HQZQJC	CHAR(8),
	HQZRSP	DECIMAL(9,3),
	HQJRKP	DECIMAL(9,3),
	HQZJCJ	DECIMAL(9,3),
	HQCJSL	DECIMAL(12,0),
	HQCJJE	DECIMAL(17,3),
	HQCJBS	DECIMAL(9,0),
	HQZGCJ	DECIMAL(9,3),
	HQZDCJ	DECIMAL(9,3),
	HQSYL1	DECIMAL(7,2),
	HQSYL2	DECIMAL(7,2),
	HQJSD1	DECIMAL(9,3),
	HQJSD2	DECIMAL(9,3),
	HQHYCC	DECIMAL(12,0),
	HQSJW5	DECIMAL(9,3),
	HQSSL5	DECIMAL(12,0),
	HQSJW4	DECIMAL(9,3),
	HQSSL4	DECIMAL(12,0),
	HQSJW3	DECIMAL(9,3),
	HQSSL3	DECIMAL(12,0),
	HQSJW2	DECIMAL(9,3),
	HQSSL2	DECIMAL(12,0),
	HQSJW1	DECIMAL(9,3),
	HQSSL1	DECIMAL(12,0),
	HQBJW1	DECIMAL(9,3),
	HQBSL1	DECIMAL(12,0),
	HQBJW2	DECIMAL(9,3),
	HQBSL2	DECIMAL(12,0),
	HQBJW3	DECIMAL(9,3),
	HQBSL3	DECIMAL(12,0),
	HQBJW4	DECIMAL(9,3),
	HQBSL4	DECIMAL(12,0),
	HQBJW5	DECIMAL(9,3),
	HQBSL5	DECIMAL(12,0),
	TS          CHAR(12)
) PARTITIONED BY (TRADDATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
STORED AS TEXTFILE
;


DROP TABLE IF EXISTS sdata.szse_sec_info;
CREATE TABLE sdata.szse_sec_info
(
	XXZQDM	CHAR(6),
	XXZQJC	CHAR(8),
	XXYWJC	CHAR(20),
	XXJYDW	DECIMAL(4,0),
	XXHYZL	CHAR(3),
	XXHBZL	CHAR(2),
	XXMGMZ	DECIMAL(7,2),
	XXZFXL	DECIMAL(12,0),
	XXLTGS	DECIMAL(12,0),
	XXSNLR	DECIMAL(9,4),
	XXBNLR	DECIMAL(9,4),
	XXJSFL	DECIMAL(7,6),
	XXYHSL	DECIMAL(7,6),
	XXGHFL	DECIMAL(7,6),
	XXSSRQ	DATE,
	XXDJRQ	DATE,
	XXMBXL	DECIMAL(9,0),
	XXBLDW	DECIMAL(6,0),
	XXSLDW	DECIMAL(6,0),
	XXJGDW	DECIMAL(5,3),
	XXJHCS	DECIMAL(7,3),
	XXLXCS	DECIMAL(7,3),
	XXXJXZ	DECIMAL(1,0),
	XXZTJG	DECIMAL(9,3),
	XXDTJG	DECIMAL(9,3),
	XXZHBL	DECIMAL(5,2),
	XXJYZT	CHAR(1),
	XXZQJB	CHAR(1),
	XXTPBZ	CHAR(1),
	XXCQCX	CHAR(1),
	XXCFBZ	CHAR(1),
	TS	    CHAR(12)
) PARTITIONED BY (TRADDATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
STORED AS TEXTFILE
;

DROP TABLE IF EXISTS sdata.szse_new_sec_info;
CREATE TABLE sdata.szse_new_sec_info
(
	XXZQDM	CHAR(6),
	XXZQJC	CHAR(8),
	XXJCQZ	CHAR(4),
	XXYWJC	CHAR(20),
	XXJCZQ	CHAR(6),
	XXISIN	CHAR(12),
	XXHYZL	CHAR(3),
	XXHBZL	CHAR(2),
	XXMGMZ	DECIMAL(7,2),
	XXZFXL	DECIMAL(12,0),
	XXLTGS	DECIMAL(12,0),
	XXSNLR	DECIMAL(9,4),
	XXBNLR	DECIMAL(9,4),
	XXLJJZ	DECIMAL(9,4),
	XXJSFL	DECIMAL(7,6),
	XXYHSL	DECIMAL(7,6),
	XXGHFL	DECIMAL(7,6),
	XXSSRQ	DATE,
	XXQXRQ	DATE,
	XXDJRQ	DATE,
	XXJYDW	DECIMAL(4,0),
	XXBLDW	DECIMAL(6,0),
	XXSLDW	DECIMAL(6,0),
	XXMBXL	DECIMAL(9,0),
	XXJGDW	DECIMAL(5,3),
	XXJHCS	DECIMAL(7,3),
	XXLXCS	DECIMAL(7,3),
	XXXJXZ	DECIMAL(1,0),
	XXZTJG	DECIMAL(9,3),
	XXDTJG	DECIMAL(9,3),
	XXJGSX	DECIMAL(9,3),
	XXJGXX	DECIMAL(9,3),
	XXZHBL	DECIMAL(5,2),
	XXDBZSL	DECIMAL(5,2),
	XXRZBD	CHAR(1),
	XXRQBD	CHAR(1),
	XXCFBZ	CHAR(1),
	XXZSBZ	CHAR(1),
	XXSCDM	CHAR(2),
	XXZQLB	CHAR(4),
	XXZQJB	CHAR(1),
	XXZQZT	CHAR(1),
	XXJYLX	CHAR(1),
	XXJYJD	CHAR(1),
	XXTPBZ	CHAR(1),
	XXRZZT	CHAR(1),
	XXRQZT	CHAR(1),
	XXRQJX	CHAR(1),
	XXWLTP	CHAR(1),
	XXYWZT	CHAR(8),
	XXGXSJ	CHAR(6),
	XXMARK	CHAR(12),
	XXBYBZ	CHAR(1),
	TS	    CHAR(12)
) PARTITIONED BY (TRADDATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
STORED AS TEXTFILE
;

